### ISSUE TITLE
Move love.html to index.html

### ISSUE THREAD

**Issue by priyansh1161** [lakshaygaba3/lakshay#1]
There is no point having a single anchor tag in index when the only thing you want is to serve love.html, so delete index.html and rename portfolio.html to index.html.

P.S if you are making a portfolio page, you may also want to rename this repo to lakshaygaba3.github.io doing this will automatically host your portfolio at http://lakshaygaba3.github.io

**Comment by lakshaygaba3** [comment]
done

**Comment by priyansh1161** [comment]
Good, but from now onwards you'll create a new Branch and will send a PR to master branch so that I can review. this flow is same for all open source projects, now since you have done this task. I'll soon create a Repo full of issues and you can fix them with the RIGHT flow.
In Addition to that, that contribution will also reflect in Hacktober fest. 🥇
